# Permalinks
permalink:        pretty

# Setup

title:            Kristina & Immo are getting married!
partner1:         Kristina
partner2:         Immo
wedding-year:     2026
wedding-month:    7
wedding-day:      25
wedding-hour:     16
wedding-tag:      July 25th, 2026 Leavenworth, Washington
wedding-location: Blue Elk Inn, Leavenworth, WA
copyright:        Immo Landwerth & Kristina Walker